set OLLAMA_INTEL_GPU=true
set OLLAMA_INTEL_IF_TYPE=SYCL
set OLLAMA_NUM_GPU=64
set OLLAMA_LIBRARY_PATH=./build/lib/ollama
set SYCL_CACHE_PERSISTENT=1
set OLLAMA_CONTEXT_LENGTH=8192
@REM set ONEAPI_ROOT=C:\Program Files (x86)\Intel\oneAPI
@REM set PATH=%PATH%;%ONEAPI_ROOT%\2025.1\bin
@REM set PATH=%PATH%;D:\GoProjects\ollama\build\lib\ollama;
set OLLAMA_KEEP_ALIVE=10m
@REM set OLLAMA_DEBUG=true
@REM set GGML_SYCL_DEBUG=1
set NO_PROXY=localhost,127.0.0.1
@REM set OLLAMA_GPU_OVERHEAD=0
@REM set OLLAMA_FLASH_ATTENTION=false
set ZES_ENABLE_SYSMAN=1
.\ollama.exe serve
